workflows:
  android:
    name: Build Android APK with Buildozer
    max_build_duration: 60
    environment:
      vars:
        BUILD_NUMBER: 1
    scripts:
      - name: Install Java 8
        script: |
          brew tap homebrew/cask-versions
          brew install --cask temurin8

      - name: Install Android Command Line Tools
        script: |
          brew install --cask android-commandlinetools
          export ANDROID_HOME=$HOME/Library/Android/sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --licenses
          sdkmanager "build-tools;35.0.0" "platforms;android-31"

      - name: Build APK
        script: |
          buildozer -v android debug

    artifacts:
      - build/*.apk

