version: 1.0

workflows:
  android:
    name: Android
    environment:
      python: "3.8"  # O la versión que estés usando
      java: "8"  # Asegúrate de que esté configurado en Java 8
    scripts:
      - name: Install dependencies
        script: |
          pip install -r requirements.txt
      - name: Build the APK
        script: |
          buildozer -v android debug

