workflows:
  android:
    name: Build Android APK with Buildozer
    max_build_duration: 60
    environment:
      java: 8
      android:
        components:
          - tools
          - platform-tools
          - build-tools-29.0.2
          - android-29

    scripts:
      - name: Install Java 8
        script: |
          brew tap homebrew/cask-versions
          brew install --cask temurin@8
          
      - name: Set Java 8
        script: |
          export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
          export PATH=$JAVA_HOME/bin:$PATH

      - name: Install Android Command Line Tools
        script: |
          brew install --cask android-commandlinetools
          export ANDROID_HOME=$HOME/Library/Android/sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --licenses
          sdkmanager "build-tools;30.0.3" "platforms;android-31"

      - name: Build APK
        script: |
          buildozer -v android debug

    artifacts:
      - build/*.apk

